### ISSUE TITLE
KH editor question 

### ISSUE THREAD

**Issue by bucanero** [Xeeynamo/psndb#2]
Hi @Xeeynamo 
sorry to open a question here, but I couldn't post on the KH editor repo.

Is there any specific reason why the KH Editor does not support PS3 saves for KH Chain of Memories? is only an offset issue, a PS3 big-endian issue, or maybe is something else? I'd like to know if you have any information about it

thanks!

**Comment by Xeeynamo** [comment]
Endian issue
